### PR TITLE
remove composer.lock from repo and add it to .gitignore

### PR DESCRIPTION
**Pull request by arubacao**
When dependencies are installed in a PHP 7.1 environment and the composer.lock reflects this, travis will fail on PHP 7.0

See: 
```
  Problem 1
    - Installation request for doctrine/annotations v1.5.0 -> satisfiable by doctrine/annotations[v1.5.0].
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
  Problem 3
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - jms/serializer 1.9.0 requires doctrine/annotations ^1.0 -> satisfiable by doctrine/annotations[v1.5.0].
    - Installation request for jms/serializer 1.9.0 -> satisfiable by jms/serializer[1.9.0].
```

### CODE REVIEW

**Comment by arubacao** [comment]
Ok, nevermind. This doesn't fix the tests since you use PHP 7.1 only syntax 
But still you shouldn't commit the composer.lock to the repo :)

**Comment by jordanbrauer** [comment]
Hey @arubacao, thanks for your submission!

Why should we not commit the lock file? I was under the impression that this is point of a lock file. 🤔 If you don't commit the lock file, every time someone clones & installs, composer will pull the most update to date version of the deps.

I am aware of being able to specify versions, but as far as I know, the only way to do that is by adding the commit hash you'd like for your dependency to the dependency entry.

Maybe I am missing something? 😆

**Comment by arubacao** [comment]
You are right about everything you wrote about the lock file.
However since this is library should be used as a dependency within other projects, composer doesn't even consider this libraries composer.lock file - only the composer.json file. Meaning that with a fresh `composer require jordanbrauer/unit-converter` you'll only get the latest possible non-dev dependencies. 

So in my experience you only need a lock file within the "end-project" and not within the dependencies.

I'm all in for only supporting the latest php versions 👍

**Comment by jordanbrauer** [comment]
Wow, I did not know that. That makes a lot more sense now, thanks. We can remove the .lockfile then!

**Pull request merged**
