### PR TITLE
Add support for PHP 8.2

### PR DESCRIPTION
**Pull request by MammutAlex**
## Types of changes

What types of changes does your code introduce? Check/place an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Description

This pull request introduces support for PHP 8.2, ensuring that the project remains compatible with the latest PHP version. By updating the codebase and making the necessary adjustments, users can benefit from the improved performance, security, and features provided by PHP 8.2.

By merging this PR, the project will stay up to date with the latest PHP version, providing users with a more secure and high-performance experience. Please review the changes and provide any feedback or suggestions.

### CODE REVIEW

**Comment by MammutAlex** [comment]
@jordanbrauer I wanted to follow up on the pull request I submitted to your PHP library for adding support for version 8.2. Could you please take a moment to review and accept the changes? It would greatly benefit the users and keep the library up to date.

**Review by jordanbrauer — APPROVED** [review]

**Comment by jordanbrauer** [comment]
So sorry that I missed this @MammutAlex. Thank you for taking care of this ^^ I have really not given this project the attention it deserves these days.

I will publish a release & check on the tests later after work. ^^

**Comment by ashleyhood** [comment]
@jordanbrauer I was wondering if this was going to be merged and a release made soon. If this is not the plan to support PHP 8.2 in the near future then it would be good to know so that I can remove this package as a dependency and freely upgrade my PHP to 8.2|8.3

**Comment by ashleyhood** [comment]
> Ah, so sorry. I've merged this and will publish later tonight.
> 
> See also #186 where I am fixing some CI related things first.
> 
> Thank you for your patience 🙏

Thank you for taking the time to work on this package, as this package is a time save for all who use it.

**Comment by jordanbrauer** [comment]
@ashleyhood @MammutAlex you can upgrade to `v0.9.0` for PHP 8 support. Really appreciate your guys' patience here. 🙇 Feel free to open a new issue or pull request if you encounter issues.

Thanks again (￣▽￣)ノ

**Pull request merged**
